# Generated by Django 3.2.13 on 2022-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='nb_max',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
