# Generated by Django 3.2.13 on 2022-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='effectif',
        ),
        migrations.AddField(
            model_name='regroupement',
            name='effectif_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
