# Generated by Django 3.2.13 on 2022-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0004_auto_20220605_1512'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cours',
            name='unique_ue_enseignant',
        ),
        migrations.AlterField(
            model_name='salle',
            name='nom',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ue',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
