# Generated by Django 3.2.13 on 2022-06-09 10:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0005_auto_20220608_1412'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.CheckConstraint(check=models.Q(('heure_fin__gt', django.db.models.expressions.F('heure_debut'))), name='check_heure_fin_gt_heure_debut'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('enseignant', 'salle', 'jour', 'heure_debut', 'heure_fin'), name='unique_enseignant_salle_jour_heure'),
        ),
    ]
